### ISSUE TITLE
The error occurred when using the name "test" to test the grayscale dataset:

### ISSUE THREAD

**Issue by DJ-APE** [hellloxiaotian/HWformer#1]
………………
  File "/home/XXX/anaconda3/envs/HWformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/XXX/anaconda3/envs/HWformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/XXX/Desktop/HWformer-main/main/../model/bformer.py", line 71, in forward
    x = self.body1(x)
  File "/home/XXX/anaconda3/envs/HWformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/XXX/Desktop/HWformer-main/main/../model_common/bformer_transformerlayer.py", line 493, in forward
    x = x.view(B, C, H // window_size, window_size, W // window_size, window_size)
RuntimeError: shape '[1, 64, 0, 96, 0, 96]' is invalid for input of size 147456

**Comment by DJ-APE** [comment]
Using python trian.py --mode test --model_name bformer --rgb_range 1 --n_colors 1 --sigma 25 --num_layers 1 --n_GPUs 1 --GPU_id 3 --test_dataset Set12 --model_file_name ../model_zoo/bformer/g25/model_sigma25.pth

**Comment by hellloxiaotian** [comment]
> Using python trian.py --mode test --model_name bformer --rgb_range 1 --n_colors 1 --sigma 25 --num_layers 1 --n_GPUs 1 --GPU_id 3 --test_dataset Set12 --model_file_name ../model_zoo/bformer/g25/model_sigma25.pth

Hello, this issue may be caused by the tensor shape being set to 0. Please check if the test dataset path is correct. Thank you.

**Comment by DJ-APE** [comment]
Sorry to bother you, but I followed the instructions in the readme to locate the path and download the dataset you provided, but I'm still getting an error.
![image](https://github.com/user-attachments/assets/560a7a52-6943-4deb-94f6-1e37fbca316b)

**Comment by hellloxiaotian** [comment]
> Sorry to bother you, but I followed the instructions in the readme to locate the path and download the dataset you provided, but I'm still getting an error. ![image](https://private-user-images.githubusercontent.com/57972441/360228625-560a7a52-6943-4deb-94f6-1e37fbca316b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTY1NzQsIm5iZiI6MTcyNDI5NjI3NCwicGF0aCI6Ii81Nzk3MjQ0MS8zNjAyMjg2MjUtNTYwYTdhNTItNjk0My00ZGViLTk0ZjYtMWUzN2ZiY2EzMTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAzMTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNWM4MGNlMGQ5ZDVlOGJhN2VkODMyODc1NjdkY2RkNjVlNzU1MWQxOGEzNjY3YjdlMGU3OTYyNjEyODUyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.THU8OLUJpU8GqSAojhR8SALxitNJEF-Ey4yK47hfyiY)

Okay, we have noticed this issue, but we need to rerun the code to find the cause of the problem. Thank you.

**Comment by hkRuan** [comment]
我也遇到了完全一样的问题：RuntimeError: shape '[1, 64, 0, 96, 0, 96]' is invalid for input of size 147456，期待和感谢您的答复。

**Comment by hellloxiaotian** [comment]
We have checked our code and find the problem. That is beaause of a wrong default  value of the "patch_size" parameter in option.py. The correct value should be 96. You can modify the value directly in option.py, or just add "--patch_size 96" behind your command.

**Comment by DJ-APE** [comment]
> We have checked our code and find the problem. That is beaause of a wrong default value of the "patch_size" parameter in option.py. The correct value should be 96. You can modify the value directly in option.py, or just add "--patch_size 96" behind your command.

Thank you for your prompt response and fix. We will try again. Thank you.
